name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-build:
    name: test build
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x, 1.18.x]
        os: [ubuntu-latest]
        include:
        - go-version: 1.18.x
          os: macos-latest
        - go-version: 1.18.x
          os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Test
      run: make test
    - name: Run linter
      uses: golangci/golangci-lint-action@v2
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        version: v1.45.0
        args: -E=gofmt --timeout=30m0s
